# PyTorch 基础 : 张量

第一章已经通过官方入门教程对PyTorch有一定了解，这一章详细介绍PyTorch的基础知识。

全部掌握这些基础知识，在后面应用中才能更加快速进阶。

In [1]:
# 引入相关的包
import torch
import numpy as np

#打印版本
torch.__version__

'1.6.0'

## 张量(Tensor)

张量英文是Tensor，是PyTorch基础运算单位，与Numpy的ndarray相同，都表示一个多维矩阵。

与ndarray最大区别，PyTorch的Tensor可以在GPU上运行，而numpy的ndarray 只能在 CPU 上运行，GPU大大加快运算速度。

生成一个简单的张量

In [2]:
x = torch.rand(2, 3)
x

tensor([[0.7235, 0.4105, 0.5354],
        [0.3968, 0.0604, 0.7637]])

以上生成一个2行3列的的矩阵：

In [3]:
# 使用与numpy相同的shape属性查看
print(x.shape)

# 使用size()函数，返回结果都相同
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


张量（Tensor）是一个定义在一些向量空间和一些对偶空间的笛卡儿积的多重线性映射，坐标是|n|维空间内有|n|个分量的一种量， 

每个分量都是坐标的函数，坐标变换时这些分量也依照某些规则作线性变换。r称为张量的秩或阶（与矩阵的秩和阶均无关系）。 

生成一些多维的张量：

In [5]:
y = torch.rand(2, 3, 4, 5)
print(y.size())
print(y.shape)
y

torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])


tensor([[[[0.8375, 0.9474, 0.0764, 0.1776, 0.4988],
          [0.8100, 0.3928, 0.7176, 0.9753, 0.6740],
          [0.2103, 0.8669, 0.3524, 0.8687, 0.2207],
          [0.7261, 0.6136, 0.2062, 0.2998, 0.6649]],

         [[0.0499, 0.4658, 0.1280, 0.2336, 0.4042],
          [0.7790, 0.7909, 0.8727, 0.6530, 0.8340],
          [0.7113, 0.1374, 0.4834, 0.1079, 0.7217],
          [0.8947, 0.6109, 0.1316, 0.5398, 0.5676]],

         [[0.7951, 0.7474, 0.2126, 0.0729, 0.2882],
          [0.1214, 0.8023, 0.4734, 0.9300, 0.1808],
          [0.2686, 0.0514, 0.5475, 0.2639, 0.8974],
          [0.5391, 0.7611, 0.0623, 0.8634, 0.6973]]],


        [[[0.8018, 0.6088, 0.1670, 0.6407, 0.9981],
          [0.3468, 0.3353, 0.8670, 0.9033, 0.6481],
          [0.7264, 0.3287, 0.3944, 0.2540, 0.9785],
          [0.6887, 0.7901, 0.7338, 0.0950, 0.5558]],

         [[0.4063, 0.6294, 0.4534, 0.7271, 0.4923],
          [0.0615, 0.6693, 0.4314, 0.0889, 0.7493],
          [0.2168, 0.0080, 0.2364, 0.7060, 0.1827],
  

同构意义下，第零阶张量 （r = 0） 为标量 （Scalar），

第一阶张量 （r = 1） 为向量 （Vector）， 

第二阶张量 （r = 2） 则成为矩阵 （Matrix），

第三阶以上的统称为多维张量。

要特别注意的就是标量，先生成一个标量：

In [6]:
# 直接用现有数字生成
scalar = torch.tensor(3.1433223)
print(scalar)

#打印标量的大小
scalar.size()

tensor(3.1433)


torch.Size([])

标量可以直接使用.item()取出对应的python对象值

In [7]:
scalar.item()

3.143322229385376

如果张量只有一个元素的tensor,也可以调用`tensor.item`方法

In [8]:
tensor = torch.tensor([3.1433223])
print(tensor)
tensor.size()

tensor([3.1433])


torch.Size([1])

In [9]:
tensor.item()

3.143322229385376

### 基本类型

Tensor基本数据类型有五种：
- 32位浮点型：torch.FloatTensor。 (默认)
- 64位整型：torch.LongTensor。
- 32位整型：torch.IntTensor。
- 16位整型：torch.ShortTensor。
- 64位浮点型：torch.DoubleTensor。

除以上数字类型外，还有byte和chart型

In [10]:
long = tensor.long()
long

tensor([3])

In [11]:
half = tensor.half()
half

tensor([3.1426], dtype=torch.float16)

In [12]:
int_t = tensor.int()
int_t

tensor([3], dtype=torch.int32)

In [13]:
flo = tensor.float()
flo

tensor([3.1433])

In [14]:
short = tensor.short()
short

tensor([3], dtype=torch.int16)

In [15]:
ch = tensor.char()
ch

tensor([3], dtype=torch.int8)

In [16]:
bt = tensor.byte()
bt

tensor([3], dtype=torch.uint8)

### Numpy转换
用numpy方法将Tensor转为ndarray

In [17]:
a = torch.randn((3, 2))

# tensor转化为numpy
numpy_a = a.numpy()
print(numpy_a)

[[-0.52589417  0.4766728 ]
 [-0.21430488  0.26101008]
 [ 0.05236792 -0.2149475 ]]


numpy转化为Tensor

In [18]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[-0.5259,  0.4767],
        [-0.2143,  0.2610],
        [ 0.0524, -0.2149]])

Tensor和numpy对象共享内存，转换很快且几乎不会消耗什么资源。

但这也意味着，如果其中一个变了，另外一个也会随之改变。

### 设备间转换
一般情况下可以使用.cuda方法将tensor移动到gpu，这步操作需要cuda设备支持

In [19]:
cpu_a = torch.rand(4, 3)
cpu_a.type()

'torch.FloatTensor'

In [20]:
gpu_a = cpu_a.cuda()
gpu_a.type()

AssertionError: Torch not compiled with CUDA enabled

使用.cpu方法将tensor移动到cpu

In [20]:
cpu_b = gpu_a.cpu()
cpu_b.type()

'torch.FloatTensor'

如果我们有多GPU的情况，可以使用to方法来确定使用那个设备，这里只做个简单的实例：

In [21]:
#使用torch.cuda.is_available()来确定是否有cuda设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
#将tensor传送到设备
gpu_b = cpu_b.to(device)
gpu_b.type()

cuda


'torch.cuda.FloatTensor'

### 初始化
Pytorch有许多默认的初始化方法可以使用

In [21]:
# [0,1]均匀分布随机初始化二维数组
rnd = torch.rand(5, 3)
rnd

tensor([[0.3521, 0.0674, 0.6069],
        [0.4133, 0.0840, 0.2918],
        [0.9048, 0.0678, 0.0620],
        [0.1962, 0.7485, 0.1544],
        [0.7735, 0.7795, 0.9825]])

In [22]:
## 初始化，用1填充
one = torch.ones(2, 2)
one

tensor([[1., 1.],
        [1., 1.]])

In [23]:
## 初始化，使用0填充
zero = torch.zeros(2, 2)
zero

tensor([[0., 0.],
        [0., 0.]])

In [24]:
# 初始化一个单位矩阵，即对角线为1 其他为0
eye = torch.eye(2, 2)
eye

tensor([[1., 0.],
        [0., 1.]])

### 常用方法
PyTorch中对张量的操作api 和 NumPy 非常相似，如果熟悉 NumPy 中的操作，那么二者基本一致：

In [25]:
x = torch.randn(3, 3)
print(x)

tensor([[ 0.3584,  2.2564,  0.3087],
        [ 0.3401,  0.0649, -0.8345],
        [ 0.9346,  1.7832,  1.2504]])


In [26]:
# 沿着行取最大值
max_value, max_idx = torch.max(x, dim=1)
print(max_value, max_idx)

tensor([2.2564, 0.3401, 1.7832]) tensor([1, 0, 1])


In [27]:
# 每行 x 求和
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([ 2.9235, -0.4295,  3.9682])


In [28]:
y = torch.randn(3, 3)
z = x + y
print(z)

tensor([[-1.2212, -0.0231,  0.0824],
        [ 0.6864, -0.7644,  0.2140],
        [ 1.1957,  1.7189,  1.1060]])


In [29]:
# add完成后x值改变
x.add_(y)
print(x)

tensor([[-1.2212, -0.0231,  0.0824],
        [ 0.6864, -0.7644,  0.2140],
        [ 1.1957,  1.7189,  1.1060]])
