In [1]:
%matplotlib inline

### PyTorch是什么?

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy替代品，使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台
    

### 开始

Tensors（张量）

Tensors与Numpy的ndarrays类似，PyTorch中Tensors可以用GPU计算

In [2]:
from __future__ import print_function
import torch
torch.__version__

'1.5.1'

创建一个 5x3 矩阵, 但是未初始化:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


创建一个随机初始化的矩阵:



In [5]:
# ?torch.rand

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5081, 0.8877, 0.2786],
        [0.5848, 0.7974, 0.9384],
        [0.2382, 0.3433, 0.9910],
        [0.5165, 0.5147, 0.4106],
        [0.7604, 0.4427, 0.7296]])


创建一个0填充的矩阵，数据类型为long:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


根据现有张量创建张量。重用输入张量属性，例如dtype，除非设置新的值覆盖

In [8]:
# new_* 方法创建对象
x = x.new_ones(5, 3, dtype=torch.double)      
print(x)

# 覆盖 dtype! 对象的size相同，只是值和类型发生变化
x = torch.randn_like(x, dtype=torch.float)    
print(x)                                     

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0148, -0.4416, -0.7658],
        [ 0.6285, -0.5004, -0.9260],
        [-0.6636,  0.1605,  1.1145],
        [ 0.1245, -0.0021,  0.2611],
        [ 0.7243,  1.5760, -0.1673]])


获取 size

使用size方法与Numpy的shape属性返回相同，张量也支持shape属性

In [9]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 返回值是 tuple类型, 所以它支持tuple类型的所有操作.</p></div>

操作有多种语法,加法运算。

加法1:

In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.5697,  0.3691, -0.4307],
        [ 1.5182,  0.3145,  0.0535],
        [-0.5642,  0.1785,  1.2584],
        [ 0.5477,  0.1335,  0.8087],
        [ 0.7881,  1.6238,  0.1498]])


加法2


In [11]:
print(torch.add(x, y))

tensor([[ 0.5697,  0.3691, -0.4307],
        [ 1.5182,  0.3145,  0.0535],
        [-0.5642,  0.1785,  1.2584],
        [ 0.5477,  0.1335,  0.8087],
        [ 0.7881,  1.6238,  0.1498]])


提供输出tensor作为参数



In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5697,  0.3691, -0.4307],
        [ 1.5182,  0.3145,  0.0535],
        [-0.5642,  0.1785,  1.2584],
        [ 0.5477,  0.1335,  0.8087],
        [ 0.7881,  1.6238,  0.1498]])


替换



In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5697,  0.3691, -0.4307],
        [ 1.5182,  0.3145,  0.0535],
        [-0.5642,  0.1785,  1.2584],
        [ 0.5477,  0.1335,  0.8087],
        [ 0.7881,  1.6238,  0.1498]])


<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

与NumPy索引方式相同的操作进行对张量操作

In [14]:
print(x[:, 1])

tensor([-0.4416, -0.5004,  0.1605, -0.0021,  1.5760])


``torch.view``: 改变张量的维度和大小

torch.view 与Numpy的reshape类似

In [15]:
x = torch.randn(4, 4)
y = x.view(16)

#  size -1 从其他维度推断
z = x.view(-1, 8)  
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果只有一个元素的张量，用``.item()``得到Python数据类型的数值

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6140])
0.6140379309654236


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

### NumPy 转换

将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个变化。

将一个Torch Tensor转换为NumPy数组

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy Array 转化成 Torch Tensor; 使用from_numpy自动转化

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有Tensor类型默认基于CPU， CharTensor类型不支持到NumPy的转换.
### CUDA 张量

``.to`` 可以将Tensor移动到任何设备中

In [21]:
# is_available 函数判断是否有cuda可用
# ``torch.device``将张量移动到指定设备
if torch.cuda.is_available():
    # CUDA设备对象
    device = torch.device("cuda")

    # 直接从GPU创建张量
    y = torch.ones_like(x, device=device)

    # 或者直接使用``.to("cuda")``将张量移动到cuda中
    x = x.to(device)
    
    z = x + y
    print(z)
    
    # ``.to`` 也会对变量的类型做更改
    print(z.to("cpu", torch.double))  